name: antitourist
publish_to: 'none'
version: 0.2.0+3

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0
  flutter_map: ^8.3.2
  latlong2: ^0.9.1
  geolocator: ^14.1.1
  url_launcher: ^6.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/demo_places.json
